version: "3.9"

services:
  react-app:
    build: .
    container_name: react_nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_URL=https://main-domain-example.win
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./app/dist:/usr/share/nginx/html:ro
    entrypoint: |
      /bin/sh -c "
      trap exit TERM;
      while :; do
        certbot renew --webroot -w /usr/share/nginx/html --quiet;
        sleep 12h & wait \$${!};
      done
      "
